
WITH parents as (
   SELECT ID AS AGENT_PARENTID, CUSTOM_CUSTOMERNAME,  AGENT_INSTANCECATEGORY, AGENT_INSTANCETYPE ,          
    CUSTOM_TR_MARKET_SEGMENT_L_1,CUSTOM_TR_MARKET_SEGMENT_L_2, CUSTOM_COUNTRY
    FROM PROD.SOURCE.PENDO_HIGHQ_ACCOUNT_HISTORY_VW
    WHERE ID IS NOT NULL and ID not like '%[a-z]%' 
   -- AND CUSTOM_TR_MARKET_SEGMENT_L_1 LIKE  'Legal Professionals'
    AND AGENT_INSTANCECATEGORY LIKE 'Client' AND AGENT_INSTANCETYPE LIKE 'Live'
    QUALIFY RANK() OVER (PARTITION BY ID ORDER BY LAST_UPDATED_AT DESC)= 1 
),
ACCOUNTS_1 AS (
    SELECT ID AS ACCOUNTID, AGENT_PARENTID, AGENT_SITEPURPOSE ,AGENT_ISSITETEMPLATE,LAST_UPDATED_AT
    FROM PROD.SOURCE.PENDO_HIGHQ_ACCOUNT_HISTORY_VW
    WHERE ID IS NOT NULL and ID not like '%[a-z]%' 
   --AND CONTAINS(lower(AGENT_SITEPURPOSE),'client portal')
   -- AND lower(AGENT_SITEPURPOSE) LIKE 'matter%'
    AND AGENT_PARENTID IN (SELECT AGENT_PARENTID FROM parents) 
    QUALIFY RANK() OVER (PARTITION BY ID ORDER BY LAST_UPDATED_AT DESC)= 1 
)
, 
ALL_ACCOUNTS AS (
SELECT A.ACCOUNTID, B.AGENT_PARENTID, A.AGENT_SITEPURPOSE ,A.AGENT_ISSITETEMPLATE, B.CUSTOM_CUSTOMERNAME,  B.AGENT_INSTANCECATEGORY, B.AGENT_INSTANCETYPE ,          
B.CUSTOM_TR_MARKET_SEGMENT_L_1,B.CUSTOM_TR_MARKET_SEGMENT_L_2, B.CUSTOM_COUNTRY
FROM ACCOUNTS_1 A left JOIN parents B ON 
A.AGENT_PARENTID= B.AGENT_PARENTID

)
, 
PAGE_EVENTS AS (
SELECT	CONCAT(day(timestamp),'-',MONTH(TIMESTAMP),'-', YEAR(TIMESTAMP)) AS DDMMYYYY, account_id, visitor_id, PAGE_ID, SUM(NUM_EVENTS) AS PAGE_VIEWS, SUM(NUM_MINUTES) AS Time_On_Page
FROM PROD.SOURCE.PENDO_HIGHQ_PAGE_EVENT_VW 
WHERE	APP_ID LIKE '-323232' AND to_date(convert_timezone('UTC','America/New_York',timestamp::timestamp_ntz)) BETWEEN '2024-11-01'  AND '2025-04-30'
GROUP BY 1,2,3,4
),

PAGE_ID AS (
SELECT Id,name,group_id	 
FROM PROD.SOURCE.PENDO_HIGHQ_PAGE_HISTORY_VW 
WHERE APP_ID LIKE '-323232'
qualify RANK() OVER (PARTITION BY id ORDER BY last_updated_at DESC)= 1	
)
,product_area as(
    select ID as group_id, Name from PROD.SOURCE.PENDO_HIGHQ_GROUP_VW
    qualify RANK() OVER (PARTITION BY id ORDER BY last_updated_at DESC)= 1	
)
,

PAGE_usage_1 as (
SELECT F.DDMMYYYY, F.ACCOUNT_ID,B.AGENT_PARENTID AS PARENT_ID, B.AGENT_SITEPURPOSE ,B.AGENT_ISSITETEMPLATE, B.CUSTOM_CUSTOMERNAME,  B.AGENT_INSTANCECATEGORY, B.AGENT_INSTANCETYPE ,          
B.CUSTOM_TR_MARKET_SEGMENT_L_1,B.CUSTOM_TR_MARKET_SEGMENT_L_2, B.CUSTOM_COUNTRY ,F.VISITOR_ID, PA.NAME AS PRODUCT_AREA,FID.NAME AS PAGE_NAME, F.PAGE_VIEWS, F.TIME_ON_PAGE
--F.* , FID.NAME,PA.NAME AS PRODUCT_AREA
FROM PAGE_EVENTS F
LEFT JOIN PAGE_ID FID ON F.PAGE_ID =FID.ID
LEFT JOIN product_area PA ON FID.GROUP_ID = PA.group_id
right join ALL_ACCOUNTS b on F.ACCOUNT_ID = B.ACCOUNTID
)

-- SELECT PAGE_NAME, SUM(PAGE_VIEWS) AS PAGE_VIEWS, COUNT(DISTINCT VISITOR_ID) AS U_USERS FROM PAGE_USAGE_1
-- where PAGE_NAME LIKE ANY ('Tasks - View - List', 'Tasks - View - Card', 'Tasks - View - Hierarchy', 'Tasks - View - Timeline')
-- AND PAGE_VIEWS > 0
-- GROUP BY 1
-- ORDER BY 2 DESC
-- ;

select * from PAGE_usage_1
-- where PAGE_NAME LIKE ANY ('Tasks - View - List', 'Tasks - View - Card', 'Tasks - View - Hierarchy', 'Tasks - View - Timeline')
where PAGE_NAME LIKE ANY ('Tasks - View - Timeline','Tasks - View - Timeline - 1 Week','Tasks - View - Timeline - 2 weeks'
,'Tasks - View - Timeline - 1 month','Tasks - View - Timeline - 3 months')
AND PAGE_VIEWS > 0
