    -- select ID as group_id, Name from PROD.SOURCE.PENDO_HIGHQ_GROUP_VW		
    -- where lower(name) like 'isheets'
    -- qualify RANK() OVER (PARTITION BY id ORDER BY last_updated_at DESC)= 1		





-- isheets specific usage
-- sysenableisheetwijmogrid


WITH		
parents as (		
    SELECT ID AS AGENT_PARENTID, CUSTOM_CUSTOMERNAME,  AGENT_INSTANCECATEGORY, AGENT_INSTANCETYPE ,          		
    CUSTOM_TR_MARKET_SEGMENT_L_1,CUSTOM_TR_MARKET_SEGMENT_L_2, CUSTOM_COUNTRY, CUSTOM_SERVERNAME, CUSTOM_INSTANCECONTEXT
    FROM PROD.SOURCE.PENDO_HIGHQ_ACCOUNT_HISTORY_VW		
    WHERE ID IS NOT NULL and ID not like '%[a-z]%' 		
    AND AGENT_INSTANCECATEGORY LIKE 'Client' AND AGENT_INSTANCETYPE LIKE 'Live'	
    AND CUSTOM_SYSENABLEISHEETWIJMOGRID = FALSE	
    QUALIFY RANK() OVER (PARTITION BY ID ORDER BY LAST_UPDATED_AT DESC)= 1 		
),		
		
ACCOUNTS_1 AS (		
    SELECT ID AS ACCOUNTID, AGENT_PARENTID, AGENT_SITEPURPOSE ,AGENT_ISSITETEMPLATE,LAST_UPDATED_AT		
    FROM PROD.SOURCE.PENDO_HIGHQ_ACCOUNT_HISTORY_VW		
    WHERE ID IS NOT NULL and ID not like '%[a-z]%' 		
    --AND CONTAINS(lower(AGENT_SITEPURPOSE),'client portal')		
    --AND AGENT_SITEPURPOSE LIKE 'Contract Management'		
    AND AGENT_PARENTID IN (SELECT AGENT_PARENTID FROM parents) 		
    QUALIFY RANK() OVER (PARTITION BY ID ORDER BY LAST_UPDATED_AT DESC)= 1 		
), 		
ALL_ACCOUNTS AS (		
SELECT A.ACCOUNTID, B.AGENT_PARENTID, A.AGENT_SITEPURPOSE ,A.AGENT_ISSITETEMPLATE, B.CUSTOM_CUSTOMERNAME,  B.AGENT_INSTANCECATEGORY, B.AGENT_INSTANCETYPE ,          		
CUSTOM_SERVERNAME, CUSTOM_INSTANCECONTEXT, B.CUSTOM_TR_MARKET_SEGMENT_L_1,B.CUSTOM_TR_MARKET_SEGMENT_L_2, B.CUSTOM_COUNTRY		
FROM ACCOUNTS_1 A LEFT JOIN parents B ON 		
A.AGENT_PARENTID= B.AGENT_PARENTID		
) 		

, 		
FEATURE_EVENTS AS (		
    SELECT		
    --cast(TIMESTAMP AS DATE) AS DDMMYYYY,		
    --CONCAT(MONTH(TIMESTAMP),'-', YEAR(TIMESTAMP)) AS MMYYYY,    		
    account_id, 		
    --visitor_id, 		
    FEATURE_ID, 		
    SUM(num_events) as feature_clicks		
	FROM	prod.source.pendo_highq_feature_event_vw
	WHERE	APP_ID LIKE '-323232' AND to_date(convert_timezone('UTC','America/New_York',timestamp::timestamp_ntz)) BETWEEN '2025-01-01' AND '2025-07-31'    
    GROUP BY 1,2
   )		
		
, feature_id as ( 		
    SELECT	id,name,group_id FROM prod.source.pendo_highq_feature_history_vw		
    --isheets PA
    where group_id like'uwbxA1BYxTeKTv-Y9ykUb7nTe0w'
    qualify RANK() OVER (PARTITION BY id ORDER BY last_updated_at DESC)= 1	
    )		
		
    ,		
product_area as(		
    select ID as group_id, Name from PROD.SOURCE.PENDO_HIGHQ_GROUP_VW		
    qualify RANK() OVER (PARTITION BY id ORDER BY last_updated_at DESC)= 1		
)		
		
SELECT 
--F.MMYYYY,
  B.AGENT_PARENTID AS PARENT_ID,
 --B.AGENT_SITEPURPOSE ,B.AGENT_ISSITETEMPLATE,
  B.CUSTOM_CUSTOMERNAME,  B.AGENT_INSTANCECATEGORY, B.AGENT_INSTANCETYPE ,          		
B.CUSTOM_TR_MARKET_SEGMENT_L_1,B.CUSTOM_TR_MARKET_SEGMENT_L_2, B.CUSTOM_COUNTRY ,	B.CUSTOM_SERVERNAME, B.CUSTOM_INSTANCECONTEXT,	
Count(distinct F.ACCOUNT_ID) AS SITES_ACTIVE,
--COUNT(DISTINCT F.VISITOR_ID) AS MAU_UNIQUE,		
--FID.NAME AS FEATURE_NAME, 
SUM(F.FEATURE_CLICKS) AS CLICKS
--, PA.NAME AS PRODUCT_AREA		
--F.* , FID.NAME,PA.NAME AS PRODUCT_AREA		
FROM FEATURE_EVENTS F		
LEFT JOIN FEATURE_ID FID ON F.FEATURE_ID =FID.ID		
LEFT JOIN product_area PA ON FID.GROUP_ID = PA.group_id		
right join ALL_ACCOUNTS b on F.ACCOUNT_ID = B.ACCOUNTID		
where fid.name is not null
GROUP BY 1,2,3,4,5,6,7,8,9
ORDER BY SITES_ACTIVE DESC

