WITH		
parents as (		
   SELECT ID AS AGENT_PARENTID, CUSTOM_CUSTOMERNAME,  AGENT_INSTANCECATEGORY, AGENT_INSTANCETYPE ,          		
    CUSTOM_TR_MARKET_SEGMENT_L_1,CUSTOM_TR_MARKET_SEGMENT_L_2, CUSTOM_COUNTRY		
    FROM PROD.SOURCE.PENDO_HIGHQ_ACCOUNT_HISTORY_VW		
    WHERE ID IS NOT NULL and ID not like '%[a-z]%' 		
    --AND CUSTOM_TR_MARKET_SEGMENT_L_1 LIKE  'Corporate'		
    AND AGENT_INSTANCECATEGORY LIKE 'Client' AND AGENT_INSTANCETYPE LIKE 'Live'		
    --AND CUSTOM_COUNTRY like 'CA'
    QUALIFY RANK() OVER (PARTITION BY ID ORDER BY LAST_UPDATED_AT DESC)= 1 		
    
)
,ACCOUNTS_1 AS (		 
    SELECT ID AS ACCOUNTID,
    AGENT_PARENTID, AGENT_SITEPURPOSE ,AGENT_ISSITETEMPLATE,LAST_UPDATED_AT		
    FROM PROD.SOURCE.PENDO_HIGHQ_ACCOUNT_HISTORY_VW		
    WHERE ID IS NOT NULL and ID not like '%[a-z]%' 		
    --AND CONTAINS(lower(AGENT_SITEPURPOSE),'client portal')		
    AND lower(AGENT_SITEPURPOSE) LIKE '%due diligence%'		
    AND AGENT_PARENTID IN (SELECT AGENT_PARENTID FROM parents) 		
    QUALIFY RANK() OVER (PARTITION BY ID ORDER BY LAST_UPDATED_AT DESC)= 1 		
),

ALL_ACCOUNTS AS (		
SELECT A.ACCOUNTID, B.AGENT_PARENTID, A.AGENT_SITEPURPOSE ,A.AGENT_ISSITETEMPLATE, B.CUSTOM_CUSTOMERNAME,  B.AGENT_INSTANCECATEGORY, B.AGENT_INSTANCETYPE ,          		
B.CUSTOM_TR_MARKET_SEGMENT_L_1,B.CUSTOM_TR_MARKET_SEGMENT_L_2, B.CUSTOM_COUNTRY		
FROM ACCOUNTS_1 A LEFT JOIN parents B ON 		
A.AGENT_PARENTID= B.AGENT_PARENTID		

) 

, 		
FEATURE_EVENTS AS (		
    SELECT		
    cast(TIMESTAMP AS DATE) AS DDMMYYYY,		
    --CONCAT(day(TIMESTAMP),':',MONTH(TIMESTAMP),':', YEAR(TIMESTAMP)) AS DDMMYYYY,    		
    account_id, 		
    visitor_id, 		
    FEATURE_ID, 		
    SUM(num_events) as feature_clicks		
	FROM	prod.source.pendo_highq_feature_event_vw
	WHERE	APP_ID LIKE '-323232' AND to_date(convert_timezone('UTC','America/New_York',timestamp::timestamp_ntz)) > '2025-01-01'    
    GROUP BY 1,2,3,4		
   
   )		
		
, feature_id as ( 		
    SELECT	id,name,group_id	
	FROM prod.source.pendo_highq_feature_history_vw	
    qualify RANK() OVER (PARTITION BY id ORDER BY last_updated_at DESC)= 1		
    )		
		
    ,		
product_area as(		
    select ID as group_id, Name from PROD.SOURCE.PENDO_HIGHQ_GROUP_VW		 
    qualify RANK() OVER (PARTITION BY id ORDER BY last_updated_at DESC)= 1		
   
)		
, FEATURE_GROUPING AS(

    SELECT DDMMYYYY, ACCOUNT_ID, VISITOR_ID, FEATURE_ID, F.NAME AS FEATURE_NAME,
     P.NAME AS PRODUCT_AREA, feature_clicks

    FROM    FEATURE_EVENTS A LEFT JOIN FEATURE_ID F ON A.FEATURE_ID=F.ID
    LEFT JOIN PRODUCT_AREA P ON F.GROUP_ID = P.GROUP_ID

    WHERE FEATURE_NAME NOT LIKE '%DO NOT USE%' 
    AND FEATURE_NAME NOT LIKE '%- to review'
    
)
, FEATURE_PRODUCTAREA_ALL AS(
select   B.CUSTOM_CUSTOMERNAME,B.AGENT_PARENTID,ACCOUNT_ID,B.AGENT_SITEPURPOSE,
 --MONTH(F.DDMMYYYY), 
-- F.PRODUCT_AREA AS F_PRODUCT_AREA,
 --COUNT(DISTINCT F.ACCOUNT_ID) AS F_SITES,
SUM(F.feature_clicks) AS CLICKS,
COUNT(DISTINCT F.visitor_id) AS F_MAU
FROM FEATURE_GROUPING F
RIGHT JOIN ALL_ACCOUNTS b on F.ACCOUNT_ID = B.ACCOUNTID		
where F.FEATURE_NAME is not null		
GROUP BY 1,2,3,4
ORDER BY CLICKS DESC
)

select * from FEATURE_PRODUCTAREA_ALL
-- SELECT  AGENT_SITEPURPOSE,
--         COUNT(DISTINCT AGENT_PARENTID) AS ACCOUNTS, 
--         COUNT(DISTINCT ACCOUNTID) AS SITES
-- FROM ACCOUNTS_1
-- GROUP BY AGENT_SITEPURPOSE
-- ORDER BY 2 DESC
-- , 
-- PAGE_EVENTS AS (
-- SELECT	
-- --CONCAT(day(timestamp),'-',MONTH(TIMESTAMP),'-', YEAR(TIMESTAMP)) AS DDMMYYYY, 
-- cast(TIMESTAMP AS DATE) AS DDMMYYYY,	
-- account_id, visitor_id, PAGE_ID, SUM(NUM_EVENTS) AS PAGE_VIEWS, SUM(NUM_MINUTES) AS Time_On_Page
-- FROM PROD.SOURCE.PENDO_HIGHQ_PAGE_EVENT_VW 
-- WHERE	APP_ID LIKE '-323232' AND to_date(convert_timezone('UTC','America/New_York',timestamp::timestamp_ntz)) > '2025-01-01'
-- GROUP BY 1,2,3,4 
-- ),

-- PAGE_ID AS (
-- SELECT Id,name,group_id	 
-- FROM PROD.SOURCE.PENDO_HIGHQ_PAGE_HISTORY_VW 
-- WHERE APP_ID LIKE '-323232'
-- qualify RANK() OVER (PARTITION BY id ORDER BY last_updated_at DESC)= 1	
-- )
-- , PAGE_I AS(
-- SELECT F.DDMMYYYY, F.ACCOUNT_ID,B.AGENT_PARENTID AS PARENT_ID, B.AGENT_SITEPURPOSE ,B.AGENT_ISSITETEMPLATE, B.CUSTOM_CUSTOMERNAME,  B.AGENT_INSTANCECATEGORY, B.AGENT_INSTANCETYPE ,          
-- B.CUSTOM_TR_MARKET_SEGMENT_L_1,B.CUSTOM_TR_MARKET_SEGMENT_L_2, B.CUSTOM_COUNTRY ,F.VISITOR_ID, PA.NAME AS PRODUCT_AREA,FID.NAME AS PAGE_NAME, F.PAGE_VIEWS, F.TIME_ON_PAGE
-- --F.* , FID.NAME,PA.NAME AS PRODUCT_AREA
-- FROM PAGE_EVENTS F
-- LEFT JOIN PAGE_ID FID ON F.PAGE_ID =FID.ID
-- LEFT JOIN product_area PA ON FID.GROUP_ID = PA.group_id
-- right join ALL_ACCOUNTS b on F.ACCOUNT_ID = B.ACCOUNTID
-- where f.PAGE_VIEWS>0
-- )



-- select f.CUSTOM_CUSTOMERNAME,F.PARENT_ID, F.DDMMYYYY, 
-- month(f.DDMMYYYY),
-- --EXTRACT(month FROM TO_DATE(F.DDMMYYYY, 'dd-MM-yyyy')),

-- F.PRODUCT_AREA AS F_PRODUCT_AREA,
--  COUNT(DISTINCT F.ACCOUNT_ID) AS F_SITES
-- ,COUNT(DISTINCT F.visitor_id) AS F_MAU
-- ,SUM(PAGE_VIEWS) AS PAGE_VIEWS
-- ,SUM(F.TIME_ON_PAGE) AS TIMEONPAGE
-- FROM Page_i f
-- GROUP BY 1,2,3,4,5