-- Use Role TR_RACHANA.P2@THOMSONREUTERS.COM
-- WRITTEN IN AUGUST, NEEDS TO BE REVIEWED IN SEPTEMBER AGAIN 
WITH ALL_HIGHQ_CONTENTIDS AS (
select CONTENTID from

PROD.SOURCE.TR_COMMUNITY_DBO_TE_CONTENT_CONTENTS_VW
where applicationid like '1BF0C477-3869-421C-87DE-F9C817C296FC'
GROUP BY 1
)
, IDEAS_HIGHQ AS (
select * from
PROD.SOURCE.TR_COMMUNITY_DBO_TELLIGENT_IDEAS_IDEAS_VW
where telligent_ideas_ideas_id IN (SELECT CONTENTID FROM ALL_HIGHQ_CONTENTIDS) 
)
, TAGS_V1 AS (
    SELECT CONTENTID, V.TAGID, V.NAME FROM 
    PROD.SOURCE.TR_COMMUNITY_DBO_TE_CONTENT_TAGGEDCONTENT_VW T  
    LEFT JOIN prod.SOURCE.TR_COMMUNITY_DBO_TE_CONTENT_TAGS_VW V ON T.TAGID =V.TAGID
)
, TAGS_V2 AS (

    SELECT CONTENTID, 
    --GROUP_CONCAT(NAME) AS TAG_NAME 
    LISTAGG(NAME, ', ') WITHIN GROUP (ORDER BY CONTENTID) AS TAG_NAME
    FROM TAGS_V1 GROUP BY 1
)


SELECT  TELLIGENT_IDEAS_IDEAS_ID, cast(CREATEDDATEUTC AS DATE) AS DDMMYYYY,  NAME,
        DESCRIPTION, TOTALVOTES, YESVOTES, NOVOTES, SCORE, URLKEY, CURRENTSTATUSID, CHALLENGEID, S.STATUS, T.TAG_NAME
FROM IDEAS_HIGHQ IH
left join PROD.SOURCE.TR_COMMUNITY_DBO_TELLIGENT_IDEAS_IDEASTATUSHISTORY_VW s on IH.CURRENTSTATUSID = s.TELLIGENT_IDEAS_IDEASTATUSHISTORY_ID
LEFT JOIN TAGS_V2 T ON IH.TELLIGENT_IDEAS_IDEAS_ID = T.CONTENTID