WITH		
parents as (		
    SELECT ID AS AGENT_PARENTID, CUSTOM_CUSTOMERNAME,  AGENT_INSTANCECATEGORY, AGENT_INSTANCETYPE ,          		
    CUSTOM_TR_MARKET_SEGMENT_L_1,CUSTOM_TR_MARKET_SEGMENT_L_2, CUSTOM_COUNTRY, CUSTOM_SYSENABLEISHEETWIJMOGRID,
    CUSTOM_ASPENABLEISHEETWIJMOGRID, CUSTOM_DATACENTER
    FROM PROD.SOURCE.PENDO_HIGHQ_ACCOUNT_HISTORY_VW		
    WHERE ID IS NOT NULL and ID not like '%[a-z]%' 		
    AND AGENT_INSTANCECATEGORY LIKE 'Client' AND AGENT_INSTANCETYPE LIKE 'Live'		
    --AND CUSTOM_ASPENABLEISHEETWIJMOGRID = TRUE
    --AND CUSTOM_SYSENABLEISHEETWIJMOGRID =TRUE
    --JUST CAN THAT WAS LAUNCHED ON 23RD AUG
    --AND UPPER(CUSTOM_DATACENTER) LIKE ANY ('CAN1','CAN2','OSH1','UAE1','UAE2')
    --AND UPPER(CUSTOM_DATACENTER) LIKE ANY ('CAN1','CAN2')
    QUALIFY RANK() OVER (PARTITION BY ID ORDER BY LAST_UPDATED_AT DESC)= 1 		
)
,
ACCOUNTS_1 AS (		
    SELECT ID AS ACCOUNTID, AGENT_PARENTID, AGENT_SITEPURPOSE ,AGENT_ISSITETEMPLATE,LAST_UPDATED_AT				
    FROM PROD.SOURCE.PENDO_HIGHQ_ACCOUNT_HISTORY_VW		
    WHERE ID IS NOT NULL and ID not like '%[a-z]%' 		
    AND AGENT_PARENTID IN (SELECT AGENT_PARENTID FROM parents) 		
    QUALIFY RANK() OVER (PARTITION BY ID ORDER BY LAST_UPDATED_AT DESC)= 1 		
), 		
ALL_ACCOUNTS AS (		
SELECT A.ACCOUNTID, B.AGENT_PARENTID, A.AGENT_SITEPURPOSE ,A.AGENT_ISSITETEMPLATE, B.CUSTOM_CUSTOMERNAME,  B.AGENT_INSTANCECATEGORY,
B.AGENT_INSTANCETYPE , B.CUSTOM_TR_MARKET_SEGMENT_L_1,B.CUSTOM_TR_MARKET_SEGMENT_L_2, B.CUSTOM_COUNTRY, B.CUSTOM_SYSENABLEISHEETWIJMOGRID,
B.CUSTOM_ASPENABLEISHEETWIJMOGRID, B.CUSTOM_DATACENTER
FROM ACCOUNTS_1 A LEFT JOIN parents B ON 		
A.AGENT_PARENTID= B.AGENT_PARENTID		
)
, 
PAGE_EVENTS AS (
SELECT	
cast(TIMESTAMP AS DATE) AS DDMMYYYY,account_id, visitor_id, PAGE_ID, SUM(NUM_EVENTS) AS PAGE_VIEWS, SUM(NUM_MINUTES) AS Time_On_Page
FROM PROD.SOURCE.PENDO_HIGHQ_PAGE_EVENT_VW 
WHERE	APP_ID LIKE '-323232' AND DDMMYYYY >= '2025-08-23' and DDMMYYYY < '2025-09-22'
GROUP BY 1,2,3,4
),
PAGE_ID AS (
SELECT Id,name,group_id	 
FROM PROD.SOURCE.PENDO_HIGHQ_PAGE_HISTORY_VW 
WHERE APP_ID LIKE '-323232'
qualify RANK() OVER (PARTITION BY id ORDER BY last_updated_at DESC)= 1	
)
,product_area as(
    select ID as group_id, Name from PROD.SOURCE.PENDO_HIGHQ_GROUP_VW
    qualify RANK() OVER (PARTITION BY id ORDER BY last_updated_at DESC)= 1	
)
,

PAGE_usage_1 as (
SELECT 
--MONTH(F.DDMMYYYY), 
--F.ACCOUNT_ID,
B.AGENT_PARENTID AS PARENT_ID, 
--B.AGENT_SITEPURPOSE ,B.AGENT_ISSITETEMPLATE, 
B.CUSTOM_CUSTOMERNAME,  B.AGENT_INSTANCECATEGORY, B.AGENT_INSTANCETYPE ,          
B.CUSTOM_TR_MARKET_SEGMENT_L_1,B.CUSTOM_TR_MARKET_SEGMENT_L_2, B.CUSTOM_COUNTRY ,B.CUSTOM_SYSENABLEISHEETWIJMOGRID,
    B.CUSTOM_ASPENABLEISHEETWIJMOGRID, B.CUSTOM_DATACENTER,
F.VISITOR_ID, PA.NAME AS PRODUCT_AREA,FID.NAME AS PAGE_NAME, SUM(F.PAGE_VIEWS), SUM(F.TIME_ON_PAGE)
--F.* , FID.NAME,PA.NAME AS PRODUCT_AREA
FROM PAGE_EVENTS F
LEFT JOIN PAGE_ID FID ON F.PAGE_ID =FID.ID
LEFT JOIN product_area PA ON FID.GROUP_ID = PA.group_id
right join ALL_ACCOUNTS b on F.ACCOUNT_ID = B.ACCOUNTID
where lower(PAGE_NAME) like 'isheets'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13
)


select * from PAGE_usage_1